apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: harness
  name: harness
  namespace: harness-system
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: harness
  type: ClusterIP
status:
  loadBalancer: {}
